/**
 * @fileoverview Bundled bright-star catalog — a curated subset of the brightest
 *   naked-eye stars with J2000 (EQJ) right ascension, declination, distance, and
 *   apparent magnitude. Feeds astronomy-engine's DefineStar so list_visible and
 *   get_sky_position can answer for named stars. Static asset, no upstream; loaded
 *   once at module init. Coordinates from the Hipparcos / Yale Bright Star catalogs.
 * @module services/ephemeris/star-catalog
 */

import type { CatalogStar } from './types.js';

/**
 * RA is in sidereal hours [0,24); Dec in degrees [-90,90]; distance in light-years.
 * The set covers the brightest stars plus the pole star — enough to answer named-star
 * queries without bundling a multi-thousand-entry table that would never fit the eight
 * DefineStar slots simultaneously anyway.
 */
export const STAR_CATALOG: readonly CatalogStar[] = [
  {
    name: 'Sirius',
    designation: 'Alpha Canis Majoris',
    raHours: 6.7525,
    decDegrees: -16.7161,
    distanceLightYears: 8.6,
    magnitude: -1.46,
  },
  {
    name: 'Canopus',
    designation: 'Alpha Carinae',
    raHours: 6.3992,
    decDegrees: -52.6957,
    distanceLightYears: 310,
    magnitude: -0.74,
  },
  {
    name: 'Rigil Kentaurus',
    designation: 'Alpha Centauri',
    raHours: 14.6601,
    decDegrees: -60.8356,
    distanceLightYears: 4.4,
    magnitude: -0.27,
  },
  {
    name: 'Arcturus',
    designation: 'Alpha Bootis',
    raHours: 14.261,
    decDegrees: 19.1825,
    distanceLightYears: 37,
    magnitude: -0.05,
  },
  {
    name: 'Vega',
    designation: 'Alpha Lyrae',
    raHours: 18.6156,
    decDegrees: 38.7837,
    distanceLightYears: 25,
    magnitude: 0.03,
  },
  {
    name: 'Capella',
    designation: 'Alpha Aurigae',
    raHours: 5.2782,
    decDegrees: 45.998,
    distanceLightYears: 43,
    magnitude: 0.08,
  },
  {
    name: 'Rigel',
    designation: 'Beta Orionis',
    raHours: 5.2423,
    decDegrees: -8.2016,
    distanceLightYears: 860,
    magnitude: 0.13,
  },
  {
    name: 'Procyon',
    designation: 'Alpha Canis Minoris',
    raHours: 7.655,
    decDegrees: 5.225,
    distanceLightYears: 11.5,
    magnitude: 0.34,
  },
  {
    name: 'Achernar',
    designation: 'Alpha Eridani',
    raHours: 1.6286,
    decDegrees: -57.2367,
    distanceLightYears: 139,
    magnitude: 0.46,
  },
  {
    name: 'Betelgeuse',
    designation: 'Alpha Orionis',
    raHours: 5.9195,
    decDegrees: 7.4071,
    distanceLightYears: 640,
    magnitude: 0.5,
  },
  {
    name: 'Hadar',
    designation: 'Beta Centauri',
    raHours: 14.0637,
    decDegrees: -60.373,
    distanceLightYears: 390,
    magnitude: 0.61,
  },
  {
    name: 'Altair',
    designation: 'Alpha Aquilae',
    raHours: 19.8464,
    decDegrees: 8.8683,
    distanceLightYears: 17,
    magnitude: 0.77,
  },
  {
    name: 'Acrux',
    designation: 'Alpha Crucis',
    raHours: 12.4433,
    decDegrees: -63.0991,
    distanceLightYears: 320,
    magnitude: 0.77,
  },
  {
    name: 'Aldebaran',
    designation: 'Alpha Tauri',
    raHours: 4.5987,
    decDegrees: 16.5093,
    distanceLightYears: 65,
    magnitude: 0.85,
  },
  {
    name: 'Antares',
    designation: 'Alpha Scorpii',
    raHours: 16.4901,
    decDegrees: -26.432,
    distanceLightYears: 550,
    magnitude: 1.09,
  },
  {
    name: 'Spica',
    designation: 'Alpha Virginis',
    raHours: 13.4199,
    decDegrees: -11.1613,
    distanceLightYears: 250,
    magnitude: 1.04,
  },
  {
    name: 'Pollux',
    designation: 'Beta Geminorum',
    raHours: 7.7553,
    decDegrees: 28.0262,
    distanceLightYears: 34,
    magnitude: 1.14,
  },
  {
    name: 'Fomalhaut',
    designation: 'Alpha Piscis Austrini',
    raHours: 22.9608,
    decDegrees: -29.6222,
    distanceLightYears: 25,
    magnitude: 1.16,
  },
  {
    name: 'Deneb',
    designation: 'Alpha Cygni',
    raHours: 20.6905,
    decDegrees: 45.2803,
    distanceLightYears: 2600,
    magnitude: 1.25,
  },
  {
    name: 'Mimosa',
    designation: 'Beta Crucis',
    raHours: 12.7953,
    decDegrees: -59.6888,
    distanceLightYears: 280,
    magnitude: 1.25,
  },
  {
    name: 'Regulus',
    designation: 'Alpha Leonis',
    raHours: 10.1395,
    decDegrees: 11.9672,
    distanceLightYears: 79,
    magnitude: 1.35,
  },
  {
    name: 'Adhara',
    designation: 'Epsilon Canis Majoris',
    raHours: 6.977,
    decDegrees: -28.9721,
    distanceLightYears: 430,
    magnitude: 1.5,
  },
  {
    name: 'Castor',
    designation: 'Alpha Geminorum',
    raHours: 7.5767,
    decDegrees: 31.8883,
    distanceLightYears: 51,
    magnitude: 1.57,
  },
  {
    name: 'Shaula',
    designation: 'Lambda Scorpii',
    raHours: 17.5602,
    decDegrees: -37.1038,
    distanceLightYears: 570,
    magnitude: 1.62,
  },
  {
    name: 'Bellatrix',
    designation: 'Gamma Orionis',
    raHours: 5.4188,
    decDegrees: 6.3497,
    distanceLightYears: 250,
    magnitude: 1.64,
  },
  {
    name: 'Elnath',
    designation: 'Beta Tauri',
    raHours: 5.4382,
    decDegrees: 28.6075,
    distanceLightYears: 130,
    magnitude: 1.65,
  },
  {
    name: 'Alnilam',
    designation: 'Epsilon Orionis',
    raHours: 5.6036,
    decDegrees: -1.2019,
    distanceLightYears: 2000,
    magnitude: 1.69,
  },
  {
    name: 'Alnitak',
    designation: 'Zeta Orionis',
    raHours: 5.6793,
    decDegrees: -1.9426,
    distanceLightYears: 800,
    magnitude: 1.74,
  },
  {
    name: 'Alioth',
    designation: 'Epsilon Ursae Majoris',
    raHours: 12.9004,
    decDegrees: 55.9598,
    distanceLightYears: 81,
    magnitude: 1.76,
  },
  {
    name: 'Dubhe',
    designation: 'Alpha Ursae Majoris',
    raHours: 11.0621,
    decDegrees: 61.751,
    distanceLightYears: 120,
    magnitude: 1.79,
  },
  {
    name: 'Mirfak',
    designation: 'Alpha Persei',
    raHours: 3.4054,
    decDegrees: 49.8612,
    distanceLightYears: 510,
    magnitude: 1.79,
  },
  {
    name: 'Polaris',
    designation: 'Alpha Ursae Minoris',
    raHours: 2.5302,
    decDegrees: 89.2641,
    distanceLightYears: 433,
    magnitude: 1.98,
  },
];
